// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/trips/trip.proto

package trips

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]int64       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_proto_trips_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trips_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_proto_trips_trip_proto_rawDescGZIP(), []int{0}
}

func (x *GenericResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenericResponse) GetData() map[string]int64 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_trips_trip_proto protoreflect.FileDescriptor

const file_proto_trips_trip_proto_rawDesc = "" +
	"\n" +
	"\x16proto/trips/trip.proto\x12\x13trackerGenericProto\"\xc0\x01\n" +
	"\x0fGenericResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x04data\x18\x03 \x03(\v2..trackerGenericProto.GenericResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\rZ\vproto/tripsb\x06proto3"

var (
	file_proto_trips_trip_proto_rawDescOnce sync.Once
	file_proto_trips_trip_proto_rawDescData []byte
)

func file_proto_trips_trip_proto_rawDescGZIP() []byte {
	file_proto_trips_trip_proto_rawDescOnce.Do(func() {
		file_proto_trips_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trips_trip_proto_rawDesc), len(file_proto_trips_trip_proto_rawDesc)))
	})
	return file_proto_trips_trip_proto_rawDescData
}

var file_proto_trips_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trips_trip_proto_goTypes = []any{
	(*GenericResponse)(nil), // 0: trackerGenericProto.GenericResponse
	nil,                     // 1: trackerGenericProto.GenericResponse.DataEntry
}
var file_proto_trips_trip_proto_depIdxs = []int32{
	1, // 0: trackerGenericProto.GenericResponse.data:type_name -> trackerGenericProto.GenericResponse.DataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_trips_trip_proto_init() }
func file_proto_trips_trip_proto_init() {
	if File_proto_trips_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trips_trip_proto_rawDesc), len(file_proto_trips_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_trips_trip_proto_goTypes,
		DependencyIndexes: file_proto_trips_trip_proto_depIdxs,
		MessageInfos:      file_proto_trips_trip_proto_msgTypes,
	}.Build()
	File_proto_trips_trip_proto = out.File
	file_proto_trips_trip_proto_goTypes = nil
	file_proto_trips_trip_proto_depIdxs = nil
}
